# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  identity-auth:
    image: identity-auth
    build:
      context: .
      dockerfile: backend/IdentityAuth/Dockerfile
    ports:
      - 5000:5000
    links:
      - sql-server-db
  
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: frontend/money/Dockerfile
    ports:
      - 80:80
    links:
      - identity-auth

  sql-server-db:
    container_name: sql-server-db
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Password1235"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"
    ports:
       - "1433:1433"
