# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  sql-server-db:
    container_name: sql-server-db
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "1Secure*Password1"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"
    ports:
       - "1433:1433"
    networks: 
       - backend

       

  identity-auth:
    image: identity-auth
    build:
      context: .
      dockerfile: backend/IdentityAuth/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - sql-server-db
    networks: 
      - frontend
      - backend
  
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: frontend/money/Dockerfile
    ports:
      - 80:80
    networks: 
      - frontend

 
networks:
  backend:
    name: backend
  frontend:
    name: frontend